apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    port 6379
    appendonly yes
    dir /data
    save ""
    protected-mode no
    requirepass your-secure-password
    masterauth your-secure-password
  sentinel.conf: |
    port 26379
    dir /data
    sentinel monitor mymaster 172.16.29.110 6379 2
    sentinel auth-pass mymaster your-secure-password
    sentinel down-after-milliseconds mymaster 3000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1