apiVersion: v1
kind: Service
metadata:
  name: redis-0
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: redis-1
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-2
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: redis-2
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-0
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-0
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-1
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-1
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-2
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-2
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel