apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-data-sentinel-0
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
  selector:
    matchLabels:
      node: k8s01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-data-sentinel-1
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
  selector:
    matchLabels:
      node: k8s02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-data-sentinel-2
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
  selector:
    matchLabels:
      node: k8s03