# Чистый HAProxy без статистики - только Redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-clean-config
  namespace: redis
data:
  haproxy.cfg: |
    global
        daemon
        maxconn 1000

    defaults
        mode tcp
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    frontend redis_frontend
        bind *:6379
        default_backend redis_backend

    backend redis_backend
        mode tcp
        balance first
        option tcp-check
        
        # Подключение и авторизация
        tcp-check connect
        tcp-check send AUTH\ admin\ ${ADMIN_PASSWORD}\r\n
        tcp-check expect string +OK
        
        # Проверка доступности
        tcp-check send PING\r\n
        tcp-check expect string +PONG
        
        # Проверка что это мастер
        tcp-check send INFO\ replication\r\n
        tcp-check expect string role:master
        
        # Закрытие соединения
        tcp-check send QUIT\r\n
        tcp-check expect string +OK
        
        # Redis серверы
        server redis-0 redis-node-0.redis-headless.redis.svc.cluster.local:6379 check inter 3s
        server redis-1 redis-node-1.redis-headless.redis.svc.cluster.local:6379 check inter 3s
        server redis-2 redis-node-2.redis-headless.redis.svc.cluster.local:6379 check inter 3s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-clean
  namespace: redis
  labels:
    app: haproxy-clean
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy-clean
  template:
    metadata:
      labels:
        app: haproxy-clean
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.9-alpine
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-haproxy-secret
              key: admin-password
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy
          readOnly: true
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache gettext
          envsubst '${ADMIN_PASSWORD}' < /usr/local/etc/haproxy/haproxy.cfg > /tmp/haproxy.cfg
          exec haproxy -f /tmp/haproxy.cfg
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: haproxy-clean-config

---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: redis
  labels:
    app: haproxy-clean
spec:
  type: LoadBalancer
  loadBalancerIP: "172.16.29.110"
  selector:
    app: haproxy-clean
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP