auth:
  enabled: true
  password: "redis-admin-password"

architecture: replication
replica:
  replicaCount: 2
  # Init containers для replica нод - создают ACL пользователей при каждом запуске
  initContainers:
  - name: setup-acl-users
    image: redis:7-alpine
    command:
    - /bin/sh
    - -c
    - |
      echo "Ожидаем запуска Redis replica..."
      sleep 30
      echo "Создаем ACL пользователей на replica..."
      redis-cli -h localhost -p 6379 -a redis-admin-password ACL SETUSER admin-user on '>admin-secure-password' '~*' '&*' '+@all' || true
      redis-cli -h localhost -p 6379 -a redis-admin-password ACL SETUSER haproxy-user on '>haproxy-check-password' '~*' '+ping' '+info' || true
      echo "ACL пользователи созданы на replica"

master:
  # Init containers для master ноды - создают ACL пользователей при каждом запуске
  initContainers:
  - name: setup-acl-users
    image: redis:7-alpine
    command:
    - /bin/sh
    - -c
    - |
      echo "Ожидаем запуска Redis master..."
      sleep 30
      echo "Создаем ACL пользователей на master..."
      redis-cli -h localhost -p 6379 -a redis-admin-password ACL SETUSER admin-user on '>admin-secure-password' '~*' '&*' '+@all' || true
      redis-cli -h localhost -p 6379 -a redis-admin-password ACL SETUSER haproxy-user on '>haproxy-check-password' '~*' '+ping' '+info' || true
      echo "ACL пользователи созданы на master"

sentinel:
  enabled: true