# redis-3nodes.yaml
# Конфигурация Redis с 3 нодами (1 master + 2 replicas)

# Архитектура: replication с Sentinel для HA
architecture: replication

# Авторизация
auth:
  enabled: false
  # password: "StrongPassword123"  # Раскомментируйте для production

# Глобальные настройки StorageClass
global:
  storageClass: "longhorn"

# Master конфигурация
master:
  count: 1
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: LoadBalancer
    loadBalancerIP: "172.16.29.110"
    annotations:
      metallb.universe.tf/address-pool: "redis-pool"
    ports:
      redis: 6379
  # Гарантируем распределение по разным нодам
  podAntiAffinityPreset: hard

# Replica конфигурация - ЗДЕСЬ указываем количество реплик
replica:
  # ВАЖНО: 2 реплики + 1 master = 3 ноды всего
  replicaCount: 2
  
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: ClusterIP
  # Гарантируем распределение по разным нодам
  podAntiAffinityPreset: hard
  
  # Автомасштабирование отключено
  autoscaling:
    enabled: false

# Sentinel для High Availability
sentinel:
  enabled: true
  # Quorum 2 из 3 для принятия решения о failover
  quorum: 2
  downAfterMilliseconds: 5000
  failoverTimeout: 10000
  parallelSyncs: 1
  
  # 3 Sentinel экземпляра (по одному в каждом поде)
  # Это автоматически, так как Sentinel запускается как sidecar
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  service:
    type: LoadBalancer
    loadBalancerIP: "172.16.29.111"
    annotations:
      metallb.universe.tf/address-pool: "redis-pool"
    ports:
      sentinel: 26379

# Дополнительная конфигурация Redis
commonConfiguration: |-
  # Оптимизация памяти
  maxmemory 1gb
  maxmemory-policy allkeys-lru
  
  # Сетевые настройки
  timeout 300
  tcp-keepalive 60
  
  # Настройки репликации
  repl-diskless-sync yes
  repl-diskless-sync-delay 5

# Метрики (отключены, включите при необходимости)
metrics:
  enabled: false
  
# Сетевая политика (отключена для простоты)
networkPolicy:
  enabled: false

# Проверка готовности с увеличенными таймаутами
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5