# redis-values.yaml
# Оптимизировано для твоего кластера с MetalLB

# Архитектура: replication с Sentinel
architecture: replication

# Авторизация (отключена для тестирования)
auth:
  enabled: false
  # password: "your-secure-password"  # Включите для production

# Master конфигурация
master:
  count: 1
  persistence:
    enabled: true
    size: 8Gi
    # Если у вас есть определённый storageClass, укажите здесь
    # storageClass: "longhorn"  # например
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: LoadBalancer
    loadBalancerIP: "172.16.29.110"  # Фиксируем IP из redis-pool
    annotations:
      metallb.universe.tf/address-pool: "redis-pool"
    ports:
      redis: 6379
  # Распределение по нодам
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: master
          topologyKey: kubernetes.io/hostname

# Replica конфигурация  
replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: ClusterIP  # Replicas только внутри кластера
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: replica
          topologyKey: kubernetes.io/hostname

# Sentinel для High Availability
sentinel:
  enabled: true
  quorum: 2  # Минимум 2 sentinel должны согласиться для failover
  downAfterMilliseconds: 5000
  failoverTimeout: 10000
  parallelSyncs: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  service:
    type: LoadBalancer
    loadBalancerIP: "172.16.29.111"  # Второй IP из redis-pool
    annotations:
      metallb.universe.tf/address-pool: "redis-pool"
    ports:
      sentinel: 26379
  # Sentinel тоже распределяем по нодам
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: sentinel
        topologyKey: kubernetes.io/hostname

# Метрики (опционально, для мониторинга)
metrics:
  enabled: false
  # Включите если используете Prometheus
  # serviceMonitor:
  #   enabled: true

# Общие настройки
commonConfiguration: |-
  # Оптимизация под ваш кластер
  maxmemory 1gb
  maxmemory-policy allkeys-lru
  timeout 300
  tcp-keepalive 60
  
# Параметры для production
# persistence:
#   existingClaim: ""  # Если есть существующие PVC