apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: redis-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.29.110-172.16.29.115
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: redis-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - redis-pool