apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-custom
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "disabled"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
volumeBindingMode: Immediate
allowVolumeExpansion: true