apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-0
  namespace: redis
  annotations:
    metallb.universe.tf/address-pool: redis-pool
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-0
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 16379
    targetPort: 16379
    name: cluster