apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: redis
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      initContainers:
      - name: config-init
        image: busybox
        command:
        - sh
        - -c
        - |
          cp /etc/config/redis.conf /etc/redis/redis.conf
        volumeMounts:
        - name: config-source
          mountPath: /etc/config
        - name: config
          mountPath: /etc/redis
      containers:
      - name: redis
        image: redis:7.0
        args:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: cluster
        volumeMounts:
        - name: config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: config
        emptyDir: {}
      - name: config-source
        configMap:
          name: redis-config-$(POD_NAME)
  volumeClaimTemplates: []