apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    appendonly no
    save ""
    protected-mode no
    requirepass your-secure-password
    masterauth your-secure-password
    cluster-announce-port 6379
    cluster-announce-bus-port 16379