apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis
spec:
  clusterIP: None  # Headless-сервис
  selector:
    app: redis-cluster
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 16379
    targetPort: 16379
    name: cluster