apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
type: Opaque
data:
  admin-password: QWRtaW5QYXNzUmFiYml0TVE= # base64-encoded "AdminPassRabbitMQ"
  app-password: QXBwUGFzc1JhYmJpdE1R # base64-encoded "AppPassRabbitMQ"