apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: redis
spec:
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxytech/haproxy-alpine:2.9
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy
        - name: lua-script
          mountPath: /usr/local/etc/haproxy/redis.lua
          subPath: redis.lua
        args:
        - -f
        - /usr/local/etc/haproxy/haproxy.cfg
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
      - name: lua-script
        configMap:
          name: haproxy-config
          items:
          - key: redis.lua
            path: redis.lua
