apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: redis
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 256

    defaults
      mode tcp
      timeout connect 10s
      timeout client 1m
      timeout server 1m

    frontend redis
      bind *:6379
      default_backend redis_backend

    backend redis_backend
      option tcp-check
      tcp-check connect
      tcp-check send "PING\r\n"
      tcp-check expect string +PONG
      tcp-check send "INFO replication\r\n"
      tcp-check expect string role:master
      server redis1 redis-0.redis-headless.redis.svc.cluster.local:6379 check
      server redis2 redis-1.redis-headless.redis.svc.cluster.local:6379 check
      server redis3 redis-2.redis-headless.redis.svc.cluster.local:6379 check
