apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: redis
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.29.110
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: haproxy
