apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: redis
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
