apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: redis
  labels:
    app: haproxy
spec:
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxytech/haproxy-alpine:2.9
          args:
            - -f
            - /usr/local/etc/haproxy/haproxy.cfg
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            - name: lua-script
              mountPath: /usr/local/etc/haproxy/redis.lua
              subPath: redis.lua
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
        - name: lua-script
          configMap:
            name: haproxy-config
            items:
              - key: redis.lua
                path: redis.lua
