apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: config-updater
          image: alpine:3.18  # Используем Alpine вместо BusyBox
          command: ['sh', '-c',
            'echo "replica-announce-ip $POD_IP" >> /etc/redis/redis.conf;
             echo "replicaof $(redis-cli -h redis-sentinel.redis.svc.cluster.local -p 26379 --raw SENTINEL get-master-addr-by-name mymaster | head -1) 6379" >> /etc/redis/redis.conf']
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis

      containers:
        - name: redis
          image: redis:7.2
          args:
            - "redis-server"
            - "/etc/redis/redis.conf"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c",
                  "sleep 30; 
                   MASTER=$(redis-cli -h redis-sentinel.redis.svc.cluster.local -p 26379 --raw SENTINEL get-master-addr-by-name mymaster | head -1);
                   redis-cli REPLICAOF $MASTER 6379 || true"]

        # Упрощенный Sentinel-агент
        - name: sentinel-agent
          image: alpine:3.18
          command: ['sh', '-c',
            'apk add --no-cache redis;
             while true; do
               current_master=$(redis-cli -h redis-sentinel.redis.svc.cluster.local -p 26379 --raw SENTINEL get-master-addr-by-name mymaster | head -1);
               if ! redis-cli -h localhost INFO replication | grep -q "master_host:$current_master"; then
                 redis-cli -h localhost REPLICAOF $current_master 6379;
               fi;
               sleep 10;
             done']
          
      volumes:
        - name: redis-config
          configMap:
            name: redis-config