apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    port 6379
    appendonly no
    dir /data
    replica-announce-ip $(POD_IP)
    protected-mode no
    bind 0.0.0.0