apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: redis
data:
  sentinel.conf: |
    port 26379
    dir /tmp
    sentinel monitor mymaster 172.16.29.110 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
    sentinel resolve-hostnames no
    sentinel announce-hostnames no
    sentinel announce-ip 172.16.29.110
    sentinel announce-port 6379