apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-sentinel
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sentinel
          image: redis:7.2
          command:
            - sh
            - -c
            - |
              echo "Waiting for redis-0 to resolve...";
              until getent hosts redis-0.redis-headless.redis.svc.cluster.local; do
                echo "Still waiting...";
                sleep 2;
              done;
              echo "Resolved. Starting sentinel...";
              exec redis-sentinel /etc/sentinel/sentinel.conf
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: config
              mountPath: /etc/sentinel
      volumes:
        - name: config
          configMap:
            name: sentinel-config
