apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-sentinel
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for redis-0.redis-headless.redis.svc.cluster.local to resolve..."
              until nslookup redis-0.redis-headless.redis.svc.cluster.local; do
                echo "Still waiting..."
                sleep 2
              done
              echo "DNS resolved."
      containers:
        - name: sentinel
          image: redis:7.2
          command: ["redis-sentinel", "/etc/sentinel/sentinel.conf"]
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: config
              mountPath: /etc/sentinel
      volumes:
        - name: config
          configMap:
            name: sentinel-config
