apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-sentinel
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sentinel
          image: bitnami/redis-sentinel:7.2
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_MASTER_NAME
              value: mymaster
            - name: REDIS_MASTER_HOST
              value: redis-0.redis-headless.redis.svc.cluster.local
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
              value: "5000"
            - name: REDIS_SENTINEL_FAILOVER_TIMEOUT
              value: "10000"
            - name: REDIS_SENTINEL_PARALLEL_SYNCS
              value: "1"
            - name: REDIS_SENTINEL_RESOLVE_HOSTNAMES
              value: "yes"
            - name: REDIS_SENTINEL_ANNOUNCE_HOSTNAMES
              value: "no"
            - name: REDIS_SENTINEL_ANNOUNCE_IP
              value: "172.16.29.110"
            - name: REDIS_SENTINEL_ANNOUNCE_PORT
              value: "6379"
            - name: REDIS_SENTINEL_PORT_NUMBER
              value: "26379"
          ports:
            - name: redis-sentinel
              containerPort: 26379