apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: [redis-sentinel]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sentinel
          image: redis:7.2
          command:
            - sh
            - -c
            - |
              echo "Ожидаем DNS внутри контейнера..."
              until nslookup redis-0.redis-headless.redis.svc.cluster.local; do sleep 2; done
              echo "DNS найден. Ждём TCP порт..."
              until nc -z redis-0.redis-headless.redis.svc.cluster.local 6379; do sleep 2; done
              echo "redis-0 доступен. Ждём дополнительно 5 секунд..."
              sleep 5
              echo "Запуск redis-sentinel через redis-server --sentinel"
              exec redis-server /etc/sentinel/sentinel.conf --sentinel
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: config
              mountPath: /etc/sentinel
      volumes:
        - name: config
          configMap:
            name: sentinel-config
