apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  clusterIP: None
  selector:
    app: redis-sentinel
  ports:
    - name: redis-sentinel
      port: 26379
      targetPort: redis-sentinel

