apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis-sentinel
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sentinel
          image: redis:7.2
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /etc/redis-conf/sentinel.conf /data/sentinel.conf
              echo "config-rewrite no" >> /data/sentinel.conf
              redis-sentinel /data/sentinel.conf
          env:
            - name: REDIS_MASTER_PASSWORD
              value: "your-secure-password"
          ports:
            - name: redis-sentinel
              containerPort: 26379
          volumeMounts:
            - name: sentinel-config
              mountPath: /etc/redis-conf
            - name: sentinel-data
              mountPath: /data
      volumes:
        - name: sentinel-config
          configMap:
            name: sentinel-config
        - name: sentinel-data
          emptyDir: {}