apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-weather
  template:
    metadata:
      labels:
        app: api-weather
    spec:
      containers:
      - name: api-weather
        image: 172.16.29.104:8083/api_weather:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD