apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-weather-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api-weather.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-weather
            port:
              number: 80
  - host: weather-proxy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-proxy
            port:
              number: 80