# redis-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis-cluster:7.2
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster-bus
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            
            # Ключевые изменения:
            - name: REDIS_NODES
              value: "redis-0,redis-1,redis-2"  # Используем короткие имена
            
            - name: REDIS_CLUSTER_REPLICAS
              value: "1"  # По 1 реплике на мастер
            
            # Только первый под создает кластер
            - name: REDIS_CLUSTER_CREATOR
              value: 
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
                operator: "Equal"
                values: ["redis-0"]
            
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_CLUSTER_ANNOUNCE_PORT
              value: "6379"
            - name: REDIS_CLUSTER_ANNOUNCE_BUS_PORT
              value: "16379"
            
            # Увеличиваем таймауты
            - name: REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP
              value: "60"
            - name: REDIS_CLUSTER_DNS_LOOKUP_RETRIES
              value: "10"
            - name: REDIS_CLUSTER_DNS_LOOKUP_SLEEP
              value: "5"
          
          # Добавляем проверку готовности
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1