apiVersion: v1
kind: Service
metadata:
  name: redis-headless         # имя сервиса
  namespace: redis-cluster     # namespace, куда устанавливается
  labels:                      # 🟢 labels должны быть внутри metadata!
    app: redis
spec:
  clusterIP: None              # ключевая часть: headless-сервис
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
    - name: cluster-bus
      port: 16379
