apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-cluster
labels:
  app: redis
spec:
  clusterIP: None  # важно: делает сервис headless
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
    - name: cluster-bus
      port: 16379
