apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-cluster
  annotations:
    # Важно для StatefulSet
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" 
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
    - name: cluster-bus
      port: 16379
  # Критически важная настройка:
  publishNotReadyAddresses: true