apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis-cluster:7.2
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster-bus-0
            - containerPort: 16380
              name: cluster-bus-1
            - containerPort: 16381
              name: cluster-bus-2
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_NODES
              value: "redis-0.redis-headless.redis-cluster.svc.cluster.local,redis-1.redis-headless.redis-cluster.svc.cluster.local,redis-2.redis-headless.redis-cluster.svc.cluster.local"
            - name: REDIS_CLUSTER_REPLICAS
              value: "0"
            - name: REDIS_CLUSTER_DYNAMIC_IPS
              value: "no"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [[ "$MY_POD_NAME" == "redis-0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                export REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16379
              elif [[ "$MY_POD_NAME" == "redis-1" ]]; then
                export REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16380
              elif [[ "$MY_POD_NAME" == "redis-2" ]]; then
                export REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16381
              fi

              export REDIS_CLUSTER_ANNOUNCE_PORT=6379
              export REDIS_CLUSTER_ANNOUNCE_IP=172.16.29.241

              sleep 30
              exec /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h 127.0.0.1 ping | grep PONG"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
