apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis-cluster:7.2
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster-bus
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_NODES
              value: "redis-0.redis-headless.redis-cluster.svc.cluster.local,redis-1.redis-headless.redis-cluster.svc.cluster.local,redis-2.redis-headless.redis-cluster.svc.cluster.local"
            - name: REDIS_CLUSTER_REPLICAS
              value: "0"
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              value: "172.16.29.241"  # 👈 Фиксированный внешний IP
            - name: REDIS_CLUSTER_ANNOUNCE_PORT
              value: "6379"
            - name: REDIS_CLUSTER_ANNOUNCE_BUS_PORT
              value: "16379"
            - name: REDIS_CLUSTER_DYNAMIC_IPS
              value: "no"
            - name: REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP
              value: "120"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [[ "$MY_POD_NAME" == "redis-0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                echo "Starting as cluster creator"
              else
                echo "Starting as cluster member"
              fi
              sleep 30
              exec /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h 127.0.0.1 ping | grep PONG"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
