# redis-headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-cluster
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"  # Важно!
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
    - name: cluster-bus
      port: 16379
  publishNotReadyAddresses: true  # Разрешаем DNS до готовности подов