apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis-cluster:7.2
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster-bus
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            
            # Исправление 1: REDIS_CLUSTER_CREATOR только для первого пода
            - name: REDIS_CLUSTER_CREATOR
              value: "yes"  # Активно только для redis-0!
            
            # Исправление 2: Задержка для DNS
            - name: REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP
              value: "30"  # Ждать 30 сек перед разрешением имён
            
            - name: REDIS_NODES
              value: "redis-0.redis-headless.redis-cluster.svc.cluster.local redis-1.redis-headless.redis-cluster.svc.cluster.local redis-2.redis-headless.redis-cluster.svc.cluster.local"
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_CLUSTER_ANNOUNCE_PORT
              value: "6379"
            - name: REDIS_CLUSTER_ANNOUNCE_BUS_PORT
              value: "16379"
            - name: REDIS_CLUSTER_DYNAMIC_IPS
              value: "yes"
          
          # Исправление 3: Проверка готовности DNS
          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - "sleep 10 && nslookup redis-headless.redis-cluster.svc.cluster.local"