apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  namespace: redis-cluster
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: cluster-bus
      port: 16379
      targetPort: 16379
