apiVersion: v1
kind: Service
metadata:
  name: api-weather
  namespace: apps
spec:
  selector:
    app: api-weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: weather-proxy
  namespace: apps
spec:
  selector:
    app: weather-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP